version: "3"
services:
  front:
    image: node:14
    ports:
      - 3000:3000
    volumes:
      - ./front:/opt/app:z
    command:
      - /bin/bash
      - -c
      - |
        cd /opt/app
        npm install
        npm start
    networks:
      - urlshortener_default
  back:
    image: node:14
    environment:
      - PORT=3003
      - MONGO_USER=root
      - MONGO_PASSWORD=shorties
      - MONGO_SERVER=mongo-server
    depends_on: 
      - mongo
    ports:
      - 8888:3003
    volumes:
      - ./back:/opt/app:z
    command: 
      - /bin/bash
      - -c
      - |
        sleep 10
        cd /opt/app
        npm install
        npx nodemon ./bin/www
    networks:
      - urlshortener_default
  redirector:
    build: ./redirector
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=shorties
      - MONGO_SERVER=mongo-server
      - MONGO_VERSION=latest
    ports: 
      - 8080:8080
    volumes:
      - ./redirector:/var/www/html:z
    depends_on: 
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: shorties
    ports:
      - 27017:27017
    networks:
      - urlshortener_default
  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: shorties
    links:
      - mongo
    networks:
      - urlshortener_default

networks:
  urlshortener_default:
    driver: bridge
